% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Z:\447 - Evaluation ponts existants\Simulation_trafic\Result\WinQSim Results Viewer.xls
%    Worksheet: M- c
%
% Auto-generated by MATLAB on 31-Mar-2020 10:09:08

% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 8);

Section = 'Twin'; % Box, Twin, TwinRed, TwinExp, TwinConc
Config = 'Mo';   % Bi, Mo
Dist = 'ExSlow';  % Split, Stand, ExFast, ExSlow

% Specify sheet
opts.Sheet = "M- c";

% Specify column names and types
opts.VariableNames = ["S10", "S20", "S30", "S40", "S50", "S60", "S70", "S80"];
opts.SelectedVariableNames = ["S10", "S20", "S30", "S40", "S50", "S60", "S70", "S80"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
TMD = table;
ranges = ["D9:K11", "D16:K17", "D22:K23", "D28:K29", "D46:K47"];
for idx = 1:length(ranges)
    opts.DataRange = ranges(idx);
    % EDIT THIS to the filepath of the Results Viewer (and uncomment)
    tb = readtable("Z:\447 - Evaluation ponts existants\Simulation_trafic\Result\WinQSim Results Viewer.xls", opts, "UseExcel", false);
    TMD = [TMD; tb]; %#ok<AGROW>
end


% %% Clear temporary variables
% clear idx opts ranges tb

flip = table2array(TMD);
VarNames = ["EQ1", "EQ2", "Eq", "GS", "GD", "MS", "MD", "DS", "DD", "DetS", "DetD"];
TMRes = array2table(flip','VariableNames',VarNames);
TMRes.E = 1.5*(TMRes.EQ1+TMRes.EQ2+TMRes.Eq);

AGB.(Section).(Config).(Dist).Mn = TMRes;

% Specify sheet
opts.Sheet = "M+ s";

% Import the data
TMD = table;
ranges = ["D9:K11", "D16:K17", "D22:K23", "D28:K29", "D46:K47"];
for idx = 1:length(ranges)
    opts.DataRange = ranges(idx);
    % EDIT THIS to the filepath of the Results Viewer (and uncomment)
    tb = readtable("Z:\447 - Evaluation ponts existants\Simulation_trafic\Result\WinQSim Results Viewer.xls", opts, "UseExcel", false);
    TMD = [TMD; tb]; %#ok<AGROW>
end

flip = table2array(TMD);
TMRes = array2table(flip','VariableNames',VarNames);
TMRes.E = 1.5*(TMRes.EQ1+TMRes.EQ2+TMRes.Eq);

AGB.(Section).(Config).(Dist).Mp = TMRes;

% Specify sheet
opts.Sheet = "V s";

% Import the data
TMD = table;
ranges = ["D9:K11", "D16:K17", "D22:K23", "D28:K29", "D46:K47"];
for idx = 1:length(ranges)
    opts.DataRange = ranges(idx);
    % EDIT THIS to the filepath of the Results Viewer (and uncomment)
    tb = readtable("Z:\447 - Evaluation ponts existants\Simulation_trafic\Result\WinQSim Results Viewer.xls", opts, "UseExcel", false);
    TMD = [TMD; tb]; %#ok<AGROW>
end

flip = table2array(TMD);
TMRes = array2table(flip','VariableNames',VarNames);
TMRes.E = 1.5*(TMRes.EQ1+TMRes.EQ2+TMRes.Eq);

AGB.(Section).(Config).(Dist).V = TMRes;

% aQ1 = 0.7; aQ2 = 0.5; aq = 0.5;
% % T69 stands for SIA 269
% ESIA.T69 = 1.5*(ESIA.EQ(1)*aQ1+ESIA.EQ(2)*aQ2+ESIA.Eq*aq);
% % Custom
% AGBSim = 1.1*9604;